app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: Pa$$word47
    pool-size: 30

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
