server:
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/mikudemo
    username: postgres
    password: password
    pool-size: 30
