server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://aa10uj0jljvyj93.c8zru88x77g2.eu-central-1.rds.amazonaws.com:5432/users_db
    username: mikolajadamski
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
